name: docs

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  python-style-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -qU pydocstyle flake8

      - name: Check docstrings
        run: pydocstyle --convention=numpy atoMEC

      - name: Lint with flake8
        run: flake8 atoMEC --count --show-source --statistics

  build-and-deploy-pages:
    needs: python-style-checks
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          #pip install -q -r docs/requirements.txt
          pip install docutils myst-parser Sphinx sphinx-rtd-theme

      - name: Check docs for broken links
        run: |
          cd docs
          make linkcheck

      - name: Install ghostscript, its fonts and latexmk
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ghostscript \
                                  fonts-freefont-otf \
                                  gsfonts \
                                  latexmk \
                                  texlive-latex-extra

      - name: Generate LaTeX code to check for errors
        run: |
          cd docs
          make apidocs
          make latex
          cd _build/latex
          latexmk -pdf -halt-on-error

      - name: Build API and docs
        run: |
          sphinx-apidoc -o docs/source/api atoMEC
          sphinx-build -W --keep-going -b html -d docs/_build/doctrees docs/source docs/_build/html
          mv -v docs/_build/html public

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
